DROP TABLE IF EXISTS projects;
CREATE TABLE projects
(
    mine_id             integer NOT NULL,
    vendor              text    NOT NULL,
    component           text    NOT NULL,
    first_version_date  text,
    latest_version_date text,
    license             text,
    versions            integer,
    source_vendor       text,
    source_component    text,
    git_created_at      text,
    git_updated_at      text,
    git_pushed_at       text,
    git_stars        integer,
    git_issues          integer,
    git_forks           integer,
    git_license         text,
    source_mine_id      integer,
    purl_name           text    NOT NULL,
    source_purl_name    text,
    verified            text,
    license_id          integer,
    git_license_id      integer,
    PRIMARY KEY (mine_id, purl_name)
);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (1, 'taballa.hp-PD', 'tablestyle', '2013-07-05', '2013-08-26', 'MIT', 8, null, null, null, null, null, null, null, null, null, null, 'tablestyle', null, null, 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'Sindre Sorhus', 'electron-debug', '2015-06-01', '2020-12-21', 'MIT', 28, 'sindresorhus', 'electron-debug', '2015-06-01', '2022-01-10', '2021-01-23', 693, 11, 55, 'MIT', 5, 'electron-debug', 'sindresorhus/electron-debug', '2022-01-11', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'Shane Harris', 'node-blob', '2019-03-21', '2019-03-21', 'MIT', 2, 'shaneharris', 'node-blob', null, null, null, null, null, null, null, 5, 'node-blob', 'shaneharris/node-blob', '2021-05-24', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'Gergely Hornich', 'sort-paths', '2016-09-03', '2018-08-18', 'MIT', 3, 'ghornich', 'sort-paths', null, null, null, null, null, null, null, 5, 'sort-paths', 'ghornich/sort-paths', '2021-05-24', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'David Frank', 'node-fetch', '2015-01-27', '2021-12-19', 'MIT', 69, 'bitinn', 'node-fetch', null, null, null, null, null, null, null, 5, 'node-fetch', 'bitinn/node-fetch', '2021-05-24', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'npmjs', 'chart.js', '2014-07-08', '2021-12-23', 'MIT', 77, 'chartjs', 'Chart.js', '2013-03-17', '2022-01-11', '2022-01-11', 55830, 113, 11333, 'MIT', 5, 'chart.js', 'chartjs/chart.js', '2022-01-11', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'Sindre Sorhus', 'p-queue', '2016-10-28', '2021-04-07', 'MIT', 34, 'sindresorhus', 'p-queue', '2016-10-28', '2022-01-12', '2021-12-15', 1879, 31, 136, 'MIT', 5, 'p-queue', 'sindresorhus/p-queue', '2022-01-11', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'Ben Newman', 'regenerator-runtime', '2014-07-04', '2021-07-22', 'MIT', 27, 'facebook', 'regenerator', '2013-10-05', '2022-01-05', '2022-01-11', 3620, 77, 1186, 'MIT', 5, 'regenerator-runtime', 'facebook/regenerator', '2022-01-11', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'Conor Hastings', 'react-syntax-highlighter', '2016-01-27', '2021-11-12', 'MIT', 121, 'react-syntax-highlighter', 'react-syntax-highlighter', '2016-01-27', '2022-01-11', '2021-11-15', 2449, 75, 195, 'MIT', 5, 'react-syntax-highlighter', 'react-syntax-highlighter/react-syntax-highlighter', '2022-01-11', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'npmjs', 'source-map-support', '2013-01-18', '2021-11-19', 'MIT', 66, 'evanw', 'node-source-map-support', '2013-01-18', '2022-01-11', '2022-01-10', 1953, 102, 226, 'MIT', 5, 'source-map-support', 'evanw/node-source-map-support', '2022-01-11', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'Etienne Lemay', 'react-dom', '2014-05-06', '2021-12-24', 'MIT', 694, 'facebook', 'react', '2013-05-24', '2022-01-12', '2022-01-11', 180572, 915, 36701, 'MIT', 5, 'react-dom', 'facebook/react', '2022-01-11', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'npmjs', 'isbinaryfile', '2012-10-09', '2021-04-29', 'MIT', 30, 'gjtorikian', 'isBinaryFile', '2012-10-08', '2021-11-24', '2021-09-24', 141, 3, 20, 'MIT', 5, 'isbinaryfile', 'gjtorikian/isbinaryfile', '2022-01-11', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'Vladimir Krivosheev', 'electron-updater', '2015-05-01', '2021-12-01', 'MIT', 224, 'electron-userland', 'electron-builder', '2015-05-21', '2022-01-12', '2022-01-12', 11707, 308, 1471, 'MIT', 5, 'electron-updater', 'electron-userland/electron-builder', '2022-01-11', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'Alexey Prokhorov', 'electron-log', '2016-05-02', '2021-12-27', 'MIT', 101, 'megahertz', 'electron-log', '2016-05-02', '2022-01-10', '2021-12-27', 899, 11, 117, 'MIT', 5, 'electron-log', 'megahertz/electron-log', '2022-01-11', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'Jake Zatecky', 'react-checkbox-tree', '2016-02-04', '2021-08-09', 'MIT', 47, 'jakezatecky', 'react-checkbox-tree', '2016-02-04', '2022-01-09', '2022-01-03', 552, 80, 165, 'MIT', 5, 'react-checkbox-tree', 'jakezatecky/react-checkbox-tree', '2022-01-11', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'React Training', 'history', '2012-04-29', '2021-12-17', 'MIT', 99, 'ReactTraining', 'history', '2015-07-18', '2021-08-12', '2021-08-12', 7099, 115, 841, 'MIT', 5, 'history', 'reacttraining/history', '2021-08-12', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'Nikhil Marathe', 'uuid', '2011-03-31', '2021-11-29', 'MIT', 34, 'uuidjs', 'uuid', '2010-12-28', '2022-01-11', '2022-01-04', 11878, 20, 797, 'MIT', 5, 'uuid', 'uuidjs/uuid', '2022-01-11', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'Jeff Barczewski', 'react', '2011-10-26', '2021-12-28', 'MIT', 739, 'facebook', 'react', '2013-05-24', '2022-01-12', '2022-01-11', 180572, 915, 36701, 'MIT', 5, 'react', 'facebook/react', '2022-01-11', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'React Training', 'react-router-dom', '2016-12-14', '2021-12-17', 'MIT', 64, 'ReactTraining', 'react-router', '2014-05-16', '2021-08-12', '2021-08-11', 43727, 59, 8505, 'MIT', 5, 'react-router-dom', 'reacttraining/react-router', '2021-08-12', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'Felix Geisendörfer', 'form-data', '2011-05-16', '2021-02-15', 'MIT', 38, 'form-data', 'form-data', '2011-05-16', '2022-01-11', '2021-11-30', 1962, 111, 256, 'MIT', 5, 'form-data', 'form-data/form-data', '2022-01-11', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'Toru Nagashima', 'abort-controller', '2017-09-29', '2019-03-30', 'MIT', 11, 'mysticatea', 'abort-controller', '2017-09-29', '2021-12-30', '2021-03-30', 258, 17, 25, 'MIT', 5, 'abort-controller', 'mysticatea/abort-controller', '2022-01-11', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (2, 'tomkp', 'react-split-pane', '2015-06-14', '2020-08-10', 'MIT', 89, 'tomkp', 'react-split-pane', '2015-03-06', '2022-01-11', '2021-11-26', 2689, 142, 345, 'MIT', 5, 'react-split-pane', 'tomkp/react-split-pane', '2022-01-11', 5614, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (3, 'Audrey Roy Greenfeld', 'binaryornot', '2013-08-17', '2017-08-03', 'BSD', 8, 'audreyr', 'binaryornot', null, null, null, null, null, null, null, 5, 'binaryornot', 'audreyr/binaryornot', '2021-05-24', 1378, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (3, 'The gRPC Authors', 'grpcio', '2015-03-30', '2021-12-16', 'Apache License 2.0', 165, null, null, null, null, null, null, null, null, null, null, 'grpcio', null, null, 850, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (3, 'Kenneth Reitz', 'requests', '2011-02-14', '2022-01-05', 'Apache 2.0', 145, 'psf', 'requests', '2011-02-13', '2022-01-11', '2022-01-11', 46668, 221, 8589, 'Apache-2.0', 5, 'requests', 'psf/requests', '2022-01-11', 552, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (3, 'Giorgos Verigakis', 'progress', '2012-04-18', '2021-07-28', 'ISC', 9, 'verigak', 'progress', '2012-04-18', '2022-01-11', '2021-11-15', 1119, 28, 161, null, 5, 'progress', 'verigak/progress', '2022-01-11', 4863, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (3, 'pypi', 'protobuf', '2008-07-10', '2021-10-29', '3-Clause BSD License', 92, 'protocolbuffers', 'protobuf', '2014-08-26', '2022-01-12', '2022-01-11', 52549, 1018, 13622, null, 5, 'protobuf', 'protocolbuffers/protobuf', '2022-01-11', 109, null);
insert into projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) values (3, 'The ICRAR DIA Team', 'crc32c', '2017-06-07', '2021-06-25', 'LGPLv2.1+', 13, 'ICRAR', 'crc32c', '2017-06-07', '2021-10-15', '2021-06-25', 26, 0, 15, null, 5, 'crc32c', 'icrar/crc32c', '2022-01-11', 5236, null);


INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'JotaB58', 'angular', null, null, '', null, 'JotaB58', 'angular', null, null, null, null, null, null, '', 5, 'jotab58/angular', 'jotab58/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'ui-router', 'angular', null, null, 'MIT', null, 'ui-router', 'angular', '2016-10-16', '2022-05-28', '2022-05-16', 309, 8, 115, 'MIT', 5, 'ui-router/angular', 'ui-router/angular', '2022-05-30', 5615, 5615);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'RadouaneRoufid', 'angular', null, null, '', null, 'RadouaneRoufid', 'angular', '2019-02-05', '2020-07-21', '2019-02-21', 10, 0, 25, '', 5, 'radouaneroufid/angular', 'radouaneroufid/angular', '2022-05-30', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'angular', 'angular', null, null, 'MIT', null, 'angular', 'angular', '2014-09-18', '2022-05-31', '2022-05-31', 81633, 1358, 21541, 'MIT', 5, 'angular/angular', 'angular/angular', '2022-05-30', 5615, 5615);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'Songyj-225', 'angular', null, null, '', null, 'Songyj-225', 'angular', '2016-12-07', '2017-10-26', '2017-03-01', 1, 0, 10, '', 5, 'songyj-225/angular', 'songyj-225/angular', '2022-05-30', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'planetoftheweb', 'angular', null, null, '', null, 'planetoftheweb', 'angular', '2014-08-27', '2022-05-19', '2021-06-09', 75, 0, 135, '', 5, 'planetoftheweb/angular', 'planetoftheweb/angular', '2022-05-30', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'bi-labor', 'angular', null, null, '', null, 'bi-labor', 'angular', '2019-02-19', '2022-02-27', '2022-03-09', 1, 0, 9, '', 5, 'bi-labor/angular', 'bi-labor/angular', '2022-05-30', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'tagtree', 'angular', null, null, '', null, 'tagtree', 'angular', '2015-03-25', '2019-08-18', '2015-05-20', 7, 2, 7, '', 5, 'tagtree/angular', 'tagtree/angular', '2022-05-30', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'roytuts', 'angular', null, null, '', null, 'roytuts', 'angular', '2019-05-01', '2022-05-20', '2022-05-04', 17, 126, 66, '', 5, 'roytuts/angular', 'roytuts/angular', '2022-05-30', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'formio', 'angular', null, null, 'MIT', null, 'formio', 'angular', '2016-07-03', '2022-05-29', '2022-05-27', 483, 350, 369, 'MIT', 5, 'formio/angular', 'formio/angular', '2022-05-30', 5615, 5615);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'alejandrarz', 'angular', null, null, '', null, 'alejandrarz', 'angular', null, null, null, null, null, null, '', 5, 'alejandrarz/angular', 'alejandrarz/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'jqwidgets', 'angular', null, null, '', null, 'jqwidgets', 'angular', '2018-08-10', '2022-04-19', '2020-04-08', 8, 0, 6, '', 5, 'jqwidgets/angular', 'jqwidgets/angular', '2022-05-30', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'scalyr', 'angular', null, null, 'MIT', null, 'scalyr', 'angular', '2013-11-19', '2022-05-30', '2022-03-07', 854, 12, 202, 'MIT', 5, 'scalyr/angular', 'scalyr/angular', '2022-05-30', 5615, 5615);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'sentry-demos', 'angular', null, null, '', null, 'sentry-demos', 'angular', '2018-01-11', '2021-10-22', '2022-03-02', 3, 4, 10, '', 5, 'sentry-demos/angular', 'sentry-demos/angular', '2022-05-30', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'dk-lan', 'angular', null, null, '', null, 'dk-lan', 'angular', '2017-06-28', '2022-04-20', '2018-05-23', 23, 0, 8, '', 5, 'dk-lan/angular', 'dk-lan/angular', '2022-05-30', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'theJavaGeek', 'angular', null, null, '', null, 'theJavaGeek', 'angular', '2017-04-02', '2021-06-11', '2017-08-27', 20, 0, 30, '', 5, 'thejavageek/angular', 'thejavageek/angular', '2022-05-30', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'htmlk', 'angular', null, null, '', null, 'htmlk', 'angular', '2016-11-08', '2022-05-21', '2016-11-09', 86, 2, 60, '', 5, 'htmlk/angular', 'htmlk/angular', '2022-05-30', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'angulardart', 'angular', null, null, 'MIT', null, 'angulardart', 'angular', '2016-06-08', '2022-05-28', '2021-10-07', 1846, 85, 231, 'MIT', 5, 'angulardart/angular', 'angulardart/angular', '2022-05-30', 5615, 5615);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'OOP-Code-Bunny', 'angular', null, null, '', null, 'OOP-Code-Bunny', 'angular', '2014-11-14', '2022-05-22', '2019-12-04', 366, 1, 338, '', 5, 'oop-code-bunny/angular', 'oop-code-bunny/angular', '2022-05-30', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'diegoalexander91', 'angular', null, null, '', null, 'diegoalexander91', 'angular', null, null, null, null, null, null, '', 5, 'diegoalexander91/angular', 'diegoalexander91/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'DigitalHERMES', 'angular', null, null, '', null, 'DigitalHERMES', 'angular', null, null, null, null, null, null, '', 5, 'digitalhermes/angular', 'digitalhermes/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'themost-framework', 'angular', null, null, '', null, 'themost-framework', 'angular', null, null, null, null, null, null, '', 5, 'themost-framework/angular', 'themost-framework/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'prathamesh6', 'angular', null, null, '', null, 'prathamesh6', 'angular', null, null, null, null, null, null, '', 5, 'prathamesh6/angular', 'prathamesh6/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'PaniJC', 'angular', null, null, '', null, 'PaniJC', 'angular', null, null, null, null, null, null, '', 5, 'panijc/angular', 'panijc/angular', '2022-03-01', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'VTS01', 'angular', null, null, '', null, 'VTS01', 'angular', null, null, null, null, null, null, '', 5, 'vts01/angular', 'vts01/angular', '2022-01-01', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'docgeni', 'angular', null, null, '', null, 'docgeni', 'angular', null, null, null, null, null, null, '', 5, 'docgeni/angular', 'docgeni/angular', '2022-01-01', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'cristianflux', 'angular', null, null, '', null, 'cristianflux', 'angular', null, null, null, null, null, null, '', 5, 'cristianflux/angular', 'cristianflux/angular', '2022-01-01', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'kmddeveloper', 'angular', null, null, '', null, 'kmddeveloper', 'angular', null, null, null, null, null, null, '', 5, 'kmddeveloper/angular', 'kmddeveloper/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'ccsyen96', 'angular', null, null, '', null, 'ccsyen96', 'angular', null, null, null, null, null, null, '', 5, 'ccsyen96/angular', 'ccsyen96/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'niranjannaidu95', 'angular', null, null, '', null, 'niranjannaidu95', 'angular', null, null, null, null, null, null, '', 5, 'niranjannaidu95/angular', 'niranjannaidu95/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'gwellan', 'angular', null, null, '', null, 'gwellan', 'angular', null, null, null, null, null, null, '', 5, 'gwellan/angular', 'gwellan/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'brayort', 'angular', null, null, '', null, 'brayort', 'angular', null, null, null, null, null, null, '', 5, 'brayort/angular', 'brayort/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'aris-creator', 'angular', null, null, '', null, 'aris-creator', 'angular', null, null, null, null, null, null, '', 5, 'aris-creator/angular', 'aris-creator/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'fabula-ui', 'angular', null, null, '', null, 'fabula-ui', 'angular', null, null, null, null, null, null, '', 5, 'fabula-ui/angular', 'fabula-ui/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'sudoforge', 'angular', null, null, '', null, 'sudoforge', 'angular', null, null, null, null, null, null, '', 5, 'sudoforge/angular', 'sudoforge/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'yasys-docker', 'angular', null, null, '', null, 'yasys-docker', 'angular', null, null, null, null, null, null, '', 5, 'yasys-docker/angular', 'yasys-docker/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'storeon', 'angular', null, null, '', null, 'storeon', 'angular', null, null, null, null, null, null, '', 5, 'storeon/angular', 'storeon/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'Kiriwill', 'angular', null, null, '', null, 'Kiriwill', 'angular', null, null, null, null, null, null, '', 5, 'kiriwill/angular', 'kiriwill/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'smnds05', 'angular', null, null, '', null, 'smnds05', 'angular', null, null, null, null, null, null, '', 5, 'smnds05/angular', 'smnds05/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'DevIntent', 'angular', null, null, '', null, 'DevIntent', 'angular', null, null, null, null, null, null, '', 5, 'devintent/angular', 'devintent/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'angular-hispano', 'angular', null, null, '', null, 'angular-hispano', 'angular', null, null, null, null, null, null, '', 5, 'angular-hispano/angular', 'angular-hispano/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'kingzlz', 'angular', null, null, '', null, 'kingzlz', 'angular', null, null, null, null, null, null, '', 5, 'kingzlz/angular', 'kingzlz/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'devNohe', 'angular', null, null, '', null, 'devNohe', 'angular', null, null, null, null, null, null, '', 5, 'devnohe/angular', 'devnohe/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'aulinadhal', 'angular', null, null, '', null, 'aulinadhal', 'angular', null, null, null, null, null, null, '', 5, 'aulinadhal/angular', 'aulinadhal/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'BeeramVineethReddy', 'angular', null, null, '', null, 'BeeramVineethReddy', 'angular', null, null, null, null, null, null, '', 5, 'beeramvineethreddy/angular', 'beeramvineethreddy/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'BryanRiveraLivia', 'angular', null, null, '', null, 'BryanRiveraLivia', 'angular', null, null, null, null, null, null, '', 5, 'bryanriveralivia/angular', 'bryanriveralivia/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'fabioanthunes', 'angular', null, null, '', null, 'fabioanthunes', 'angular', null, null, null, null, null, null, '', 5, 'fabioanthunes/angular', 'fabioanthunes/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'grumpywizards', 'angular', null, null, '', null, 'grumpywizards', 'angular', null, null, null, null, null, null, '', 5, 'grumpywizards/angular', 'grumpywizards/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'geneseframework', 'angular', null, null, '', null, 'geneseframework', 'angular', null, null, null, null, null, null, '', 5, 'geneseframework/angular', 'geneseframework/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'master-style', 'angular', null, null, '', null, 'master-style', 'angular', null, null, null, null, null, null, '', 5, 'master-style/angular', 'master-style/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'theodorejb', 'angular', null, null, '', null, 'theodorejb', 'angular', null, null, null, null, null, null, '', 5, 'theodorejb/angular', 'theodorejb/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'imgix', 'angular', null, null, '', null, 'imgix', 'angular', null, null, null, null, null, null, '', 5, 'imgix/angular', 'imgix/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'situlive', 'angular', null, null, '', null, 'situlive', 'angular', null, null, null, null, null, null, '', 5, 'situlive/angular', 'situlive/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'ProjectAthenia', 'angular', null, null, '', null, 'ProjectAthenia', 'angular', null, null, null, null, null, null, '', 5, 'projectathenia/angular', 'projectathenia/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'ChristianJusset', 'angular', null, null, '', null, 'ChristianJusset', 'angular', null, null, null, null, null, null, '', 5, 'christianjusset/angular', 'christianjusset/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'ayepez1975', 'angular', null, null, '', null, 'ayepez1975', 'angular', null, null, null, null, null, null, '', 5, 'ayepez1975/angular', 'ayepez1975/angular', '2021-08-01', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'Cyberkabil10', 'angular', null, null, '', null, 'Cyberkabil10', 'angular', null, null, null, null, null, null, '', 5, 'cyberkabil10/angular', 'cyberkabil10/angular', '2021-08-01', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'dart-lang', 'angular', null, null, '', null, 'dart-lang', 'angular', null, null, null, null, null, null, '', 5, 'dart-lang/angular', 'dart-lang/angular', null, 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'cgarcia1208', 'angular', null, null, '', null, 'cgarcia1208', 'angular', null, null, null, null, null, null, '', 5, 'cgarcia1208/angular', 'cgarcia1208/angular', '2021-07-02', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'maniortiz98', 'angular', null, null, '', null, 'maniortiz98', 'angular', null, null, null, null, null, null, '', 5, 'maniortiz98/angular', 'maniortiz98/angular', '2021-07-02', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'rgalicia0729', 'angular', null, null, '', null, 'rgalicia0729', 'angular', null, null, null, null, null, null, '', 5, 'rgalicia0729/angular', 'rgalicia0729/angular', '2021-06-01', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'MartinAlejandroDiaz', 'angular', null, null, '', null, 'MartinAlejandroDiaz', 'angular', null, null, null, null, null, null, '', 5, 'martinalejandrodiaz/angular', 'martinalejandrodiaz/angular', '2022-03-01', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'muhamad', 'angular', null, null, '', null, 'muhamad', 'angular', null, null, null, null, null, null, '', 5, 'muhamad/angular', 'muhamad/angular', '2022-03-01', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'VicatS', 'angular', null, null, '', null, 'VicatS', 'angular', null, null, null, null, null, null, '', 5, 'vicats/angular', 'vicats/angular', '2022-03-01', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'dyywork', 'angular', null, null, '', null, 'dyywork', 'angular', '2018-01-23', '2019-02-19', '2018-11-23', 17, 1, 8, '', 5, 'dyywork/angular', 'dyywork/angular', '2021-08-12', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'becerraaabm', 'angular', null, null, '', null, 'becerraaabm', 'angular', null, null, null, null, null, null, '', 5, 'becerraaabm/angular', 'becerraaabm/angular', '2021-07-02', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'protoarch', 'angular', null, null, '', null, 'protoarch', 'angular', null, null, null, null, null, null, '', 5, 'protoarch/angular', 'protoarch/angular', '2021-09-01', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'xochy', 'angular', null, null, '', null, 'xochy', 'angular', null, null, null, null, null, null, '', 5, 'xochy/angular', 'xochy/angular', '2021-09-01', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'arthasjoshimar', 'angular', null, null, '', null, 'arthasjoshimar', 'angular', null, null, null, null, null, null, '', 5, 'arthasjoshimar/angular', 'arthasjoshimar/angular', '2021-09-01', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'srinijammula', 'angular', null, null, '', null, 'srinijammula', 'angular', null, null, null, null, null, null, '', 5, 'srinijammula/angular', 'srinijammula/angular', '2021-06-01', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'rmenai-blueprints', 'angular', null, null, '', null, 'rmenai-blueprints', 'angular', null, null, null, null, null, null, '', 5, 'rmenai-blueprints/angular', 'rmenai-blueprints/angular', '2022-03-01', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'matheo', 'angular', null, null, 'MIT', null, 'matheo', 'angular', '2019-03-18', '2022-04-06', '2022-04-20', 53, 11, 13, 'MIT', 5, 'matheo/angular', 'matheo/angular', '2022-05-30', 5615, 5615);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'pe-task', 'angular', null, null, '', null, 'pe-task', 'angular', '2019-06-06', '2019-08-02', '2022-06-01', 3, 21, 18, '', 5, 'pe-task/angular', 'pe-task/angular', '2022-05-30', 2, 2);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'bclinkinbeard', 'angular', null, null, 'MIT', null, 'bclinkinbeard', 'angular', '2013-10-27', '2019-08-13', '2017-01-20', 53, 8, 23, 'MIT', 5, 'bclinkinbeard/angular', 'bclinkinbeard/angular', '2022-05-30', 5615, 5615);
INSERT INTO projects (mine_id, vendor, component, first_version_date, latest_version_date, license, versions, source_vendor, source_component, git_created_at, git_updated_at, git_pushed_at, git_stars, git_issues, git_forks, git_license, source_mine_id, purl_name, source_purl_name, verified, license_id, git_license_id) VALUES (5, 'grails-profiles', 'angular', null, null, '', null, 'grails-profiles', 'angular', '2016-09-01', '2020-05-13', '2020-07-29', 6, 4, 4, '', 5, 'grails-profiles/angular', 'grails-profiles/angular', null, 2, 2);



